### day_1 numpy using  python

In [1]:
# Numpy_Arrays

In [2]:
import numpy as np

In [3]:
# 1dimentional array
a = np.array([4,7,8])
a

array([4, 7, 8])

In [4]:
print(type(a))

<class 'numpy.ndarray'>


In [5]:
print(len(a))

3


In [6]:
print(a.shape)

(3,)


In [ ]:
# 2 dimentional array

In [7]:
b = np.array([[1,2,3] , [4,7,8]])
b


array([[1, 2, 3],
       [4, 7, 8]])

In [8]:
print(type(b))

<class 'numpy.ndarray'>


In [9]:
print(b.shape)

(2, 3)


In [10]:
a[:1] # slicing an array

array([4])

In [11]:
b[1:]

array([[4, 7, 8]])

In [54]:
b

array([[1, 2, 3],
       [4, 7, 8]])

In [58]:
b[1][2] # from b array

8

## Numpy functions

In [62]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C')
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of zeros with the given shape, dtype, and order.
    
    See Also
    --------
    zeros_like : Return an array of zeros with shape and type of input.
    empty : Return a new uninitialized array.
    ones : Return a new array setting values to one.
    full : Return a new array of given shape filled with value.
    
 

In [61]:
np.zeros([5,5]) 

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [66]:
np.zeros([2,3] , dtype = float) # dtype is used to mention whether to get 
                               #  the answer in float or int or in complex form

array([[0., 0., 0.],
       [0., 0., 0.]])

In [72]:
# np.ones((4,7)) # use np.ones([4,7])  gives the same answer

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [69]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [74]:
np.random.random([4,8]) # it creates the random number

array([[0.4881806 , 0.22648701, 0.20733673, 0.93770434, 0.74705239,
        0.49466157, 0.3419709 , 0.08020367],
       [0.55781286, 0.27959994, 0.04538141, 0.79551711, 0.0481668 ,
        0.53379378, 0.62556934, 0.49999316],
       [0.9475598 , 0.46826557, 0.64076138, 0.96564406, 0.18291212,
        0.24001764, 0.60799802, 0.6409155 ],
       [0.59151942, 0.66098323, 0.16671259, 0.86426576, 0.5270902 ,
        0.09845261, 0.5340381 , 0.68884688]])

In [75]:
np.full([4,5] , 7) 
# first box refers the no of rows and columns and after the#
# comma , it refers what the number you have to give

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [77]:
c = np.ones_like(a)
c   # to change the a normal array to some array

array([1, 1, 1])

### Slicing

In [78]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [80]:
b = a[1:3 , :1]
b

array([[5],
       [9]])

In [81]:
b = a[:2, 1:3]
b

array([[2, 3],
       [6, 7]])

In [ ]:
# row slicing and column slicing

In [14]:
a = np.array([[4,5],[7,8],[1,2]])
a

array([[4, 5],
       [7, 8],
       [1, 2]])

In [17]:
np.shape(a)

(3, 2)

### Boolean array indexing

In [18]:
a

array([[4, 5],
       [7, 8],
       [1, 2]])

In [21]:
bool = a>=2
bool    # if the value of a in the matrix is > 2 it prints true and it prints false

array([[ True,  True],
       [ True,  True],
       [False,  True]])

In [22]:
# to know the values  the a value is > 2
a[a>2]

array([4, 5, 7, 8])

### Array math 

In [26]:
x = np.array([[7,6] , [2,1]] , dtype = np.float64)
y = np.array([[4,7] , [1,5]] ,dtype = np.float64)
print(x)

[[7. 6.]
 [2. 1.]]


In [27]:
print(y)

[[4. 7.]
 [1. 5.]]


In [28]:
#Addition
print(x+y)

[[11. 13.]
 [ 3.  6.]]


In [30]:
print(np.add(x,y)) # same ans with differnt value

[[11. 13.]
 [ 3.  6.]]


In [29]:
print(x-y)

[[ 3. -1.]
 [ 1. -4.]]


In [31]:
# multiplication
print(np.multiply(x,y))

[[28. 42.]
 [ 2.  5.]]


In [32]:
print(np.divide(x,y)) # division

[[1.75       0.85714286]
 [2.         0.2       ]]


In [34]:
print(np.sqrt(x,y))

[[2.64575131 2.44948974]
 [1.41421356 1.        ]]


In [36]:
print(np.dot(x,y))

[[27.00554055 23.1464282 ]
 [ 6.70571618  5.89897949]]


In [37]:
a = np.array([4,7])
b = np.array([1,5])  # 1 dimentional

In [38]:
a,b

(array([4, 7]), array([1, 5]))

In [39]:
print(np.dot(a,b))

39


In [40]:
# 2 dimentional
print(np.dot(x,b))

[37.  7.]


In [ ]:
## some functions in numpy
# aggregate functions

In [41]:
x

array([[7., 6.],
       [2., 1.]])

In [42]:
x = np.array([[4,8,7,1] ,[5,1,0,2]])
x

array([[4, 8, 7, 1],
       [5, 1, 0, 2]])

In [43]:
print(np.sum(x))

28


In [48]:
print(np.sum(x , axis = 0))

[9 9 7 3]


In [ ]:
# transpose

In [49]:
help(np.transpose)

Help on function transpose in module numpy:

transpose(a, axes=None)
    Permute the dimensions of an array.
    
    Parameters
    ----------
    a : array_like
        Input array.
    axes : list of ints, optional
        By default, reverse the dimensions, otherwise permute the axes
        according to the values given.
    
    Returns
    -------
    p : ndarray
        `a` with its axes permuted.  A view is returned whenever
        possible.
    
    See Also
    --------
    moveaxis
    argsort
    
    Notes
    -----
    Use `transpose(a, argsort(axes))` to invert the transposition of tensors
    when using the `axes` keyword argument.
    
    Transposing a 1-D array returns an unchanged view of the original array.
    
    Examples
    --------
    >>> x = np.arange(4).reshape((2,2))
    >>> x
    array([[0, 1],
           [2, 3]])
    
    >>> np.transpose(x)
    array([[0, 2],
           [1, 3]])
    
    >>> x = np.ones((1, 2, 3))
    >>> np.transpose(x, (1, 0, 2)).s

In [50]:
np.transpose(a)

array([4, 7])

In [51]:
np.transpose(x)

array([[4, 5],
       [8, 1],
       [7, 0],
       [1, 2]])

In [ ]:
# broadcasting

In [70]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [71]:
v = np.array([1,1,1])
v

array([1, 1, 1])

In [72]:
y = x + v
print(y)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]
 [11 12 13]]


In [63]:
x + v

array([5, 1, 3])

In [68]:
y = x + v
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [65]:
v = np.array([1, 0, 1])
v

array([1, 0, 1])

In [67]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
