In [1]:
import pandas as pd
import numpy as np

In [43]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn import tree
from time import time
from sklearn import preprocessing
from sklearn.metrics import confusion_matrix

In [4]:
data = pd.read_csv("datasets_11657_16098_train.csv")
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.6+ KB


In [6]:
data.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [8]:
data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [9]:
data.describe(include= "all")

PassengerId    Survived      Pclass                              Name  \
count    891.000000  891.000000  891.000000                               891   
unique          NaN         NaN         NaN                               891   
top             NaN         NaN         NaN  Holm, Mr. John Fredrik Alexander   
freq            NaN         NaN         NaN                                 1   
mean     446.000000    0.383838    2.308642                               NaN   
std      257.353842    0.486592    0.836071                               NaN   
min        1.000000    0.000000    1.000000                               NaN   
25%      223.500000    0.000000    2.000000                               NaN   
50%      446.000000    0.000000    3.000000                               NaN   
75%      668.500000    1.000000    3.000000                               NaN   
max      891.000000    1.000000    3.000000                               NaN   

         Sex         Age       SibSp       Parch Ticket        Fare  \
count    891  714.000000  891.000000  891.000000    891  891.000000   
unique     2         NaN         NaN         NaN    681         NaN   
top     male         NaN         NaN         NaN   1601         NaN   
freq     577         NaN         NaN         NaN      7         NaN   
mean     NaN   29.699118    0.523008    0.381594    NaN   32.204208   
std      NaN   14.526497    1.102743    0.806057    NaN   49.693429   
min      NaN    0.420000    0.000000    0.000000    NaN    0.000000   
25%      NaN   20.125000    0.000000    0.000000    NaN    7.910400   
50%      NaN   28.000000    0.000000    0.000000    NaN   14.454200   
75%      NaN   38.000000    1.000000    0.000000    NaN   31.000000   
max      NaN   80.000000    8.000000    6.000000    NaN  512.329200   

              Cabin Embarked  
count           204      889  
unique          147        3  
top     C23 C25 C27        S  
freq              4      644  
mean            NaN      NaN  
std             NaN      NaN  
min             NaN      NaN  
25%             NaN      NaN  
50%             NaN      NaN  
75%             NaN      NaN  
max             NaN      NaN

In [19]:
# instead of NaN values in the Age and Emabarked data ,so we have to change the NaN values to the median of the age

data["Age"].fillna(data["Age"].median() , inplace = True)
data["Embarked"].fillna(data["Embarked"].mode()[0] , inplace = True)

In [20]:
label_encoder = preprocessing.LabelEncoder()

In [21]:
label_encoder.fit(data["Sex"])

LabelEncoder()

In [22]:
print(label_encoder.classes_)

[0 1]


In [23]:
data["Sex"] = label_encoder.transform(data["Sex"])

In [24]:
data["Sex"]

0      1
1      0
2      0
3      0
4      1
5      1
6      1
7      1
8      0
9      0
10     0
11     0
12     1
13     1
14     0
15     0
16     1
17     1
18     0
19     0
20     1
21     1
22     0
23     1
24     0
25     0
26     1
27     1
28     0
29     1
      ..
861    1
862    0
863    0
864    1
865    0
866    0
867    1
868    1
869    1
870    1
871    0
872    1
873    1
874    0
875    0
876    1
877    1
878    1
879    0
880    0
881    1
882    0
883    1
884    1
885    0
886    1
887    0
888    0
889    1
890    1
Name: Sex, Length: 891, dtype: int64

In [25]:
# changing the text of Embarked to the numerical value
data['Embarked'].loc[data['Embarked'] == 'C'] = 0
data['Embarked'].loc[data['Embarked'] == 'Q'] = 1
data['Embarked'].loc[data['Embarked'] == 'S'] = 2

C:\Users\BHUBESH\Anaconda2\lib\site-packages\pandas\core\indexing.py:190: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)


In [31]:
# taking the target variable as Dependent variable
y = data["Sex"] #DV 
X = data.drop(["Sex" ,"PassengerId" , "Name" ,"Cabin","Ticket" ],axis =1)
# IDV

In [32]:
y.count()

891

In [35]:
# training the data uding train_test_split of sklearn
X_train , X_test , y_train ,y_test = train_test_split(X , y, test_size = 0.5 ,random_state =0 )

In [36]:
X_train.head()

Survived  Pclass   Age  SibSp  Parch     Fare  Embarked
213         0       2  30.0      0      0  13.0000         2
586         0       2  47.0      0      0  15.0000         2
499         0       3  24.0      0      0   7.7958         2
821         1       3  27.0      0      0   8.6625         2
246         0       3  25.0      0      0   7.7750         2

In [26]:
# finding the NaN values in the dataset
data.isnull().any().any()

True

In [27]:
# we got true so , there is the NaN value is present in the datset
# so, we have to remove the NaN values or have to change the NaN valeus
df_vals = data.fillna(0)

In [37]:
X = np.nan_to_num(X)# the nan values are converted to the values 

# Naive_Bayes_

### IDV => Sex
### DV = > remaining features 

In [38]:
from sklearn.naive_bayes import *

In [39]:
# lets take 
clf = GaussianNB()

In [40]:
y_pred = clf.fit(X_train , y_train).predict(X_test)

In [41]:
accuracy_score(y_test , y_pred , normalize = True)

0.7937219730941704

In [44]:
confusion_matrix(y_test , y_pred)

array([[109,  49],
       [ 43, 245]], dtype=int64)

# Naive_Bayes_2

### IDV => PClass
###  DV = > Remaining Features

In [45]:
# taking the target variable as Dependent variable
y = data["Pclass"] #DV 
X = data.drop(["Pclass" ,"PassengerId" , "Name" ,"Cabin","Ticket" ],axis =1)
# IDV

In [46]:
X_train , X_test , y_train ,y_test = train_test_split(X , y, test_size = 0.5 ,random_state =0 )

In [47]:
X_train.head()

Survived  Sex   Age  SibSp  Parch     Fare  Embarked
213         0    1  30.0      0      0  13.0000         2
586         0    1  47.0      0      0  15.0000         2
499         0    1  24.0      0      0   7.7958         2
821         1    1  27.0      0      0   8.6625         2
246         0    0  25.0      0      0   7.7750         2

In [49]:
data.isnull().any().any()

True

In [50]:
clf = GaussianNB()

In [51]:
y_pred = clf.fit(X_train , y_train).predict(X_test)

In [52]:
accuracy_score(y_test , y_pred , normalize = True)

0.695067264573991

In [53]:
confusion_matrix(y_test , y_pred)

array([[ 68,  29,  11],
       [  5,  48,  34],
       [  8,  49, 194]], dtype=int64)

# Naive_Bayes_3

## IDV => SibSp
### DV = > Remaining Features

In [57]:
y = data["SibSp"] #DV 
X = data.drop(["SibSp" ,"PassengerId" , "Name" ,"Cabin","Ticket" ],axis =1)
X_train , X_test , y_train ,y_test = train_test_split(X , y, test_size = 0.5 ,random_state =0 )
clf = GaussianNB()
y_pred = clf.fit(X_train , y_train).predict(X_test)
accuracy_score(y_test , y_pred , normalize = True)

0.6614349775784754

In [60]:
X_train.head()

Survived  Pclass  Sex   Age  Parch     Fare  Embarked
213         0       2    1  30.0      0  13.0000         2
586         0       2    1  47.0      0  15.0000         2
499         0       3    1  24.0      0   7.7958         2
821         1       3    1  27.0      0   8.6625         2
246         0       3    0  25.0      0   7.7750         2

In [58]:
confusion_matrix(y_test , y_pred)

array([[267,  24,   0,  18,   0,   0,   0],
       [ 65,  14,   0,  19,   0,   0,   0],
       [  8,   3,   0,   3,   0,   0,   0],
       [  2,   0,   0,   4,   4,   0,   0],
       [  0,   0,   0,   3,   8,   0,   0],
       [  0,   0,   0,   1,   1,   1,   0],
       [  0,   0,   0,   0,   0,   0,   1]], dtype=int64)

# Naive_Bayes_3

In [62]:
y = data["Parch"] #DV 
X = data.drop(["Parch" ,"PassengerId" , "Name" ,"Cabin","Ticket" ],axis =1)
X_train , X_test , y_train ,y_test = train_test_split(X , y, test_size = 0.5 ,random_state =0 )
clf = GaussianNB()
y_pred = clf.fit(X_train , y_train).predict(X_test)
accuracy_score(y_test , y_pred , normalize = True)

0.7399103139013453

In [63]:
X_train.head()

Survived  Pclass  Sex   Age  SibSp     Fare  Embarked
213         0       2    1  30.0      0  13.0000         2
586         0       2    1  47.0      0  15.0000         2
499         0       3    1  24.0      0   7.7958         2
821         1       3    1  27.0      0   8.6625         2
246         0       3    0  25.0      0   7.7750         2

In [64]:
confusion_matrix(y_test , y_pred)

array([[302,  22,   5,   3,  16,   0,   0],
       [ 32,  14,  10,   2,   4,   0,   0],
       [ 12,   5,  14,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0],
       [  1,   0,   0,   1,   0,   0,   0],
       [  2,   0,   0,   0,   0,   0,   0],
       [  1,   0,   0,   0,   0,   0,   0]], dtype=int64)

In [ ]:
# Next method to do the same data in for loop to find the accuracy of the data and the confision matrix of the data feature