In [4]:
import numpy as np

# Question : 1
### Create a 3x3x3 array with random values

In [12]:
x = np.random.random((3,3,3))
x

array([[[0.31505609, 0.20747925, 0.28897344],
        [0.59955549, 0.7077268 , 0.75998069],
        [0.11976053, 0.03238683, 0.29630015]],

       [[0.41596416, 0.93167856, 0.7898461 ],
        [0.78953297, 0.12121604, 0.5125003 ],
        [0.79921727, 0.42754875, 0.00217993]],

       [[0.35265786, 0.80781699, 0.54284062],
        [0.99639558, 0.81662474, 0.54027415],
        [0.18783584, 0.82550556, 0.96003625]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [6]:
import numpy as np

In [8]:
x = np.diag([1,2,3,4,5])
x

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

# Create a 8x8 matrix and fill it with a checkerboard pattern

In [18]:
x = np.zeros((3,3))
x = np.zeros((8,8),dtype = int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [19]:
x= np.random.random((5,5))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[0.11537762 0.39459932 0.37886337 0.95149468 0.08340947]
 [0.23563096 0.27347598 0.20195511 0.05102692 0.93246535]
 [0.75624521 0.46685674 0.67201913 0.65111953 0.84153869]
 [0.74931524 0.8529465  0.50444896 0.30567813 0.34311352]
 [0.05436194 0.93265232 0.18805484 0.56295953 0.51327273]]
After normalization:
[[0.07146364 0.38154881 0.3640735  1.         0.03596192]
 [0.20500905 0.24703723 0.16761088 0.         0.97886728]
 [0.78316884 0.46179313 0.68963292 0.6664232  0.87789014]
 [0.77547287 0.89055891 0.50354056 0.28279881 0.32437208]
 [0.00370365 0.97907492 0.15217415 0.56851854 0.51333965]]


# How to find common values between two arrays?

In [20]:
help(np.intersect1d)

Help on function intersect1d in module numpy:

intersect1d(ar1, ar2, assume_unique=False, return_indices=False)
    Find the intersection of two arrays.
    
    Return the sorted, unique values that are in both of the input arrays.
    
    Parameters
    ----------
    ar1, ar2 : array_like
        Input arrays. Will be flattened if not already 1D.
    assume_unique : bool
        If True, the input arrays are both assumed to be unique, which
        can speed up the calculation.  Default is False.
    return_indices : bool
        If True, the indices which correspond to the intersection of the two
        arrays are returned. The first instance of a value is used if there are
        multiple. Default is False.
    
        .. versionadded:: 1.15.0
    
    Returns
    -------
    intersect1d : ndarray
        Sorted 1D array of common and unique elements.
    comm1 : ndarray
        The indices of the first occurrences of the common values in `ar1`.
        Only provided if `retur

In [ ]:
#take two array of elrments

In [24]:
arr1 = np.array([4,5,3,6])
arr2 = np.array([7,8,6,3])
arr3 = np.intersect1d([arr1] , [arr2])
print("the common values between two arrays:",arr3)

the common values between two arrays: [3 6]


# 6.How to get the dates of yesterday, today and tomorrow?

In [27]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yesterday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tommorrow: ",tomorrow)

Yesterday:  2020-07-24
Today:  2020-07-25
Tommorrow:  2020-07-26


In [30]:
x = np.array([4,8,2,11,10])
print("First array:")
print(x)
y = np.array([4,8,2,11,10])
print("Second array:")
print(y)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)

First array:
[ 4  8  2 11 10]
Second array:
[ 4  8  2 11 10]
Test above two arrays are equal or not!
True


# 8.Create random vector of size 10 and replace the maximum value by 0

In [32]:
import numpy as np
x = np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()] = -1
print("Maximum value replaced by -1:")
print(x)

Original array:
[0.54520724 0.43462935 0.98946338 0.14308161 0.63333706 0.6329804
 0.42263924 0.28900092 0.74208589 0.76214805]
Maximum value replaced by -1:
[ 0.54520724  0.43462935 -1.          0.14308161  0.63333706  0.6329804
  0.42263924  0.28900092  0.74208589  0.76214805]


# 9. How to print all the values of an array?

In [34]:
a = np.array([4,7,8,25,12,20,35])
a

array([ 4,  7,  8, 25, 12, 20, 35])

# 10.Subtract the mean of each row of a matrix

In [7]:
print("Original matrix:\n")
x = np.random.rand(6, 15)
print(x)
print("\nSubtract the mean of each row of the said matrix:\n")
z = x - x.mean(axis=1, keepdims=True)
print(z)

Original matrix:

[[0.07031904 0.50409973 0.96913135 0.0741632  0.68514314 0.525629
  0.69025074 0.92069685 0.11633763 0.99417939 0.43260548 0.85262979
  0.38689254 0.55862339 0.53969137]
 [0.65620547 0.89611198 0.11197376 0.67637872 0.29494965 0.86625621
  0.34289383 0.92344992 0.71532335 0.50693564 0.93000272 0.53149419
  0.48734019 0.08978797 0.30475508]
 [0.58550194 0.25197717 0.07028096 0.5667191  0.36589536 0.86859215
  0.26534151 0.19454344 0.16270284 0.04886909 0.89753033 0.76104087
  0.92062439 0.6499604  0.14210018]
 [0.99221197 0.45294864 0.14222043 0.65725306 0.83648824 0.71731366
  0.59419952 0.2947671  0.11444713 0.25584249 0.76477784 0.69491405
  0.86682236 0.73663362 0.31836342]
 [0.79805907 0.86606343 0.00188101 0.47484622 0.90902966 0.44845162
  0.61148893 0.46146489 0.39269477 0.66272102 0.70866693 0.72339466
  0.75959051 0.22389091 0.93644042]
 [0.81118468 0.35281011 0.24100688 0.17956948 0.8641874  0.05547831
  0.94644292 0.72343937 0.15911633 0.84721219 0.15744197

# 11. consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [10]:
a = np.ones(10)
b = np.random.randint(0,len(a),20)
a += np.bincount(I, minlength=len(a))
print(a)

[2. 4. 3. 3. 2. 1. 3. 4. 4. 4.]


# 12.How to get the diagonal of a dot product?

In [16]:
 a = np.arange(15).reshape(5, 3)
 b = np.arange(9).reshape(3, 3)

In [17]:
np.diag(np.dot(np.dot(a, b), a.T))

array([  60,  672, 1932, 3840, 6396])

# 13 . How to find the most frequent value in an array?

In [19]:
x = np.random.randint(0, 14, 35)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[ 9  0 11  5 12  4  5  8  1  7  7  1  2  4  4  8  0 11  1  4  5  4 11  2
  2  2  5  7  0  6  3  1  2  0 13]
Most frequent value in the above array:
2


# 14.How to get the n largest values of an array

In [20]:
x = np.arange(10)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])

Original array:
[0 1 2 3 4 5 6 7 8 9]
[9]


# 15.How to create a record array from a regular array?

In [24]:
a1=np.array([1,2,3,4])
a2=np.array(['bhubesh','charan','karan','stephen'])
a3=np.array([50,15,20,40])
result= np.core.records.fromarrays([a1, a2, a3],names='a,b,c')
print(result[0])
print(result[1])
print(result[2])

(1, 'bhubesh', 50)
(2, 'charan', 15)
(3, 'karan', 20)
