In [31]:
import pandas as pd
import numpy as np
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score , confusion_matrix
from sklearn import preprocessing

In [18]:
train = pd.read_csv("datasets_11657_16098_train.csv")
test = pd.read_csv("datasets_122398_315766_test.csv")

In [19]:
# count missing values in train age data is missing is more 
train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [7]:
# filing the nan value with some avg age 

In [125]:
train["Age"].median()

28.0

In [127]:
new_age_var = train["Age"].fillna(titanic_train["Age"].median())

In [16]:
new_age_var # the nan values are filled with median values 

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
5      28.0
6      54.0
7       2.0
8      27.0
9      14.0
10      4.0
11     58.0
12     20.0
13     39.0
14     14.0
15     55.0
16      2.0
17     28.0
18     31.0
19     28.0
20     35.0
21     34.0
22     15.0
23     28.0
24      8.0
25     38.0
26     28.0
27     19.0
28     28.0
29     28.0
       ... 
861    21.0
862    48.0
863    28.0
864    24.0
865    42.0
866    27.0
867    31.0
868    28.0
869     4.0
870    26.0
871    47.0
872    33.0
873    47.0
874    28.0
875    15.0
876    20.0
877    19.0
878    28.0
879    56.0
880    25.0
881    33.0
882    22.0
883    28.0
884    25.0
885    39.0
886    27.0
887    19.0
888    28.0
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [ ]:
# creating a target one and the features

In [32]:
# using the label encoder to convert the text to the numerical
label_encoder = preprocessing.LabelEncoder()

In [48]:
encoded_sex = label_encoder.fit_transform(train["Sex"])

In [54]:
y_target = train["Survived"].values # dependent variable
x_features_one = pd.DataFrame(encoded_sex)

In [55]:
# splitting the data into traiining and validation sets 

x_train , x_validation , y_train , y_validation = train_test_split(x_features_one , y_target , test_size = .25 , random_state = 1)

In [59]:
# first descision tree
tree_one = tree.DecisionTreeClassifier()

In [60]:
tree_one = tree_one.fit(x_features_one , y_target)

In [61]:
tree_one

DecisionTreeClassifier()

In [82]:
with open("tree1.dot" , 'w') as f:
    f = tree.export_graphviz(tree_one , feature_names = ["Sex"] , out_file = f)

In [73]:
# the score of the included features 
# findin the accuracy of the data
tree_one_accuracy = round(tree_one.score(x_features_one , y_target),4)

In [74]:
print("Accuracy: 0.4f" % (tree_one_accuracy))

Accuracy: 0.4f


In [78]:
# predicting the y_target given validation set
predictions = tree_one.predict(x_validation)
confusion_matrix(y_validation , predictions)

array([[111,  17],
       [ 31,  64]], dtype=int64)

In [80]:
# predicted output from the tree_one model 
accuracy_score(y_validation , predictions)

0.7847533632286996

# ID = "Survived"
# IDV = "Fare"

In [93]:
# creating a target value for the survived and fare
y_target = train["Survived"].values # dependent variable
x_features_two = pd.DataFrame(train["Fare"])

In [94]:
# second descision tree
tree_two = tree.DecisionTreeClassifier()

In [95]:
tree_two = tree_two.fit(x_features_two , y_target)

In [96]:
tree_two

DecisionTreeClassifier()

In [121]:
# creating a decsion tree
with open("tree2.dot" , 'w') as f:
    f = tree.export_graphviz(tree_two, feature_names = ["Fare"] , out_file = f)

In [122]:
# findin the accuracy of the data
tree_two_accuracy = round(tree_two.score(x_features_two , y_target),4)

In [123]:
tree_two_accuracy

0.8036

In [124]:
# predicting the y_target given validation set
predictions = tree_two.predict(x_validation)
confusion_matrix(y_validation , predictions) 

array([[128,   0],
       [ 95,   0]], dtype=int64)

In [104]:
accuracy_score(y_validation , predictions)

0.5739910313901345

# IDV = "Age"
# DV = "Survived"

In [106]:
y_target = train["Survived"].values # dependent variable
x_features_three = pd.DataFrame(new_age_var)

In [107]:
# third descision tree
tree_three = tree.DecisionTreeClassifier()

In [109]:
tree_three = tree_three.fit(x_features_three , y_target)

In [110]:
tree_three

DecisionTreeClassifier()

In [117]:
with open("tree3.dot" , 'w') as f:
    f = tree.export_graphviz(tree_three, feature_names = ["Age"] ,out_file =f )

In [118]:
tree_three_accuracy = round(tree_three.score(x_features_three , y_target),4)

In [119]:
tree_three_accuracy

0.6689

In [128]:
# predicting the y_target given validation set
predictions = tree_three.predict(x_validation)
confusion_matrix(y_validation , predictions)

array([[  0, 128],
       [  0,  95]], dtype=int64)

In [130]:
accuracy_score(y_validation , predictions)

0.4260089686098655